In [7]:
import numpy as np
array = np.array([[4,3,2],
             [5,6,7]])
print(array)

[[4 3 2]
 [5 6 7]]


In [8]:
print('number of dim:', array.ndim)
print('shape:', array.shape)
print('size:', array.size)

number of dim: 2
shape: (2, 3)
size: 6


In [10]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
a = np.linspace(1,10,5).reshape((5,1))
print(a)

[[  1.  ]
 [  3.25]
 [  5.5 ]
 [  7.75]
 [ 10.  ]]


In [17]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(10*np.sin(a))

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [18]:
print(b)
print(b<3)

[0 1 2 3]
[ True  True  True False]


In [19]:
a = np.array([[10,20],
              [30,40]])
b = np.arange(4).reshape((2,2))

In [20]:
print(a*b)

[[  0  20]
 [ 60 120]]


In [21]:
c_ = np.dot(a, b)
print(c_)

[[ 40  70]
 [ 80 150]]


In [22]:
print(a.dot(b))

[[ 40  70]
 [ 80 150]]


In [27]:
a = np.random.random((2,4))
print(a)
print(np.sum(a,axis=1))

[[ 0.61803694  0.85397425  0.27896167  0.95457785]
 [ 0.13966112  0.67161935  0.79413807  0.73412336]]
5.04509261436


In [41]:
A = np.arange(0,12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
np.argmin(A)

0

In [31]:
np.argmax(A,axis=0)

array([2, 2, 2, 2])

In [32]:
np.mean(A)

7.5

In [34]:
A.mean()

7.5

In [36]:
np.average(A)

7.5

In [37]:
np.median(A)

7.5

In [38]:
np.cumsum(A)

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90])

In [39]:
np.diff(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [42]:
np.nonzero(A)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [44]:
np.sort(A)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
np.transpose(A)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [47]:
(A.T).dot(A)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [48]:
np.clip(A,5,9)

array([[5, 5, 5, 5],
       [5, 5, 6, 7],
       [8, 9, 9, 9]])

In [49]:
np.mean(A,axis=0)

array([ 4.,  5.,  6.,  7.])

In [50]:
np.mean(A,axis=1)

array([ 1.5,  5.5,  9.5])

In [53]:
A = np.arange(3,15).reshape(3,4)
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [59]:
print(A[2,1],A[2][1])

12 12


In [61]:
print(A[1,:])

[ 7  8  9 10]


In [62]:
print(A[:,1])

[ 4  8 12]


In [63]:
print(A[1,2:3])

[9]


In [64]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [65]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [66]:
for item in A.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


In [67]:
print(A.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [69]:
A = np.array([1,1,1])
B = np.array([2,2,2])

In [73]:
c=np.vstack((A,B))
print(c)


[[1 1 1]
 [2 2 2]]


In [74]:
A.shape
c.shape

(2, 3)

In [76]:
print(np.hstack((A,B)))

[1 1 1 2 2 2]


In [79]:
A.T
A
A==A.T

array([ True,  True,  True], dtype=bool)

In [90]:
print(A.shape)
print(A)
print(A.T)
A[np.newaxis,:].shape
A[:,np.newaxis].shape
A=np.array([1,1,1])

(3, 1)
[[1]
 [1]
 [1]]
[[1 1 1]]


In [84]:
np.array([1,1,1])[:,np.newaxis]


array([[1],
       [1],
       [1]])

In [93]:
np.concatenate((A,B,B,A),axis=0)

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1])

In [95]:
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [96]:
np.split(A,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [97]:
data = np.random.randint(0, 5, [3,2,3])

In [100]:
print(data)

[[[0 1 4]
  [0 3 0]]

 [[4 1 1]
  [0 2 1]]

 [[2 0 3]
  [3 2 1]]]


In [102]:
(data.T)

array([[[0, 4, 2],
        [0, 0, 3]],

       [[1, 1, 0],
        [3, 2, 2]],

       [[4, 1, 3],
        [0, 1, 1]]])

In [104]:
data.sum(axis=1)

array([[0, 4, 4],
       [4, 3, 2],
       [5, 2, 4]])

In [2]:
import numpy as np
A = np.arange(12).reshape((3,4))

print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
np.array_split(A,3,axis = 1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [4]:
np.vsplit(A,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame(np.arange(12).reshape((3,4)))
df

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [7]:
df2 = pd.DataFrame(np.arange(12).reshape((3,4)),index = np.arange(1,4),columns = ['a','b','c','d'])
df2

a  b   c   d
1  0  1   2   3
2  4  5   6   7
3  8  9  10  11

In [8]:
row = np.arange(1,4)
type(row)

numpy.ndarray

In [9]:
s = pd.Series([1,3,4,np.nan,44,1])
s

0     1.0
1     3.0
2     4.0
3     NaN
4    44.0
5     1.0
dtype: float64

In [10]:
dates = pd.date_range('20160101',periods=6)
dates

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
df2.dtypes

a    int64
b    int64
c    int64
d    int64
dtype: object

In [12]:
df2.index

Int64Index([1, 2, 3], dtype='int64')

In [13]:
df2.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [14]:
df2.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
df2.describe()


a    b     c     d
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0

In [19]:
df2

a  b   c   d
1  0  1   2   3
2  4  5   6   7
3  8  9  10  11

In [20]:
df2.T

1  2   3
a  0  4   8
b  1  5   9
c  2  6  10
d  3  7  11

In [26]:
df2.sort_index(axis = 0,ascending=False)

a  b   c   d
3  8  9  10  11
2  4  5   6   7
1  0  1   2   3

In [22]:
df2

a  b   c   d
1  0  1   2   3
2  4  5   6   7
3  8  9  10  11

In [27]:
df2.dtypes

a    int64
b    int64
c    int64
d    int64
dtype: object

In [31]:
df2.sort_values(by = 'a', ascending=False)

a  b   c   d
3  8  9  10  11
2  4  5   6   7
1  0  1   2   3

In [32]:
dates

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')

In [49]:

df = pd.DataFrame(np.arange(24).reshape((6,4)),index = dates,columns=['A','B','C','D'])
df

A   B   C   D
2016-01-01   0   1   2   3
2016-01-02   4   5   6   7
2016-01-03   8   9  10  11
2016-01-04  12  13  14  15
2016-01-05  16  17  18  19
2016-01-06  20  21  22  23

In [50]:
df.iloc[2,2] = 1111

In [51]:
df

A   B     C   D
2016-01-01   0   1     2   3
2016-01-02   4   5     6   7
2016-01-03   8   9  1111  11
2016-01-04  12  13    14  15
2016-01-05  16  17    18  19
2016-01-06  20  21    22  23

In [52]:
 df.loc['20160101','B']=2222

In [59]:
df

A     B     C   D  F   G
2016-01-01   0  2222     2   3  0 NaN
2016-01-02   4     5     6   7  1 NaN
2016-01-03   8     9  1111  11  2 NaN
2016-01-04  12    13    14  15  3 NaN
2016-01-05  16    17    18  19  4 NaN
2016-01-06   0    21    22  23  5 NaN

In [54]:
df.A[df.A>16]=0

In [56]:
df['F']=np.arange(6)

In [58]:
df['G']=np.nan